working_directory: /projects/standard/mcgaughs/drabe004/BIGFISHGENOME_DataRespository/SelectionTests

environment:
  module: hyphy/2.5.96

paths:
  alignment_directory: /projects/standard/mcgaughs/drabe004/BIGFISHGENOME_DataRespository/Orthocaller_Codon_Alignments/PAL2NAL_alns_V9_ShortestDist_DefaultBranchReassignments_Patched/cleanedforSelTestsNoStopCodons/NoCavefishAlns
  tree_directory: /projects/standard/mcgaughs/drabe004/BIGFISHGENOME_DataRespository/SelectionTests/Trees_for_Hyphy_BRAv9/Trees_for_Hyphy_BRAv9_patch/PatchedTrees/DropTrees
  output_directory: /projects/standard/mcgaughs/drabe004/BIGFISHGENOME_DataRespository/SelectionTests/BUSTED-E_FGBG_OUT_BRAv9_DROP_patch
  log_directory: BUSTED_FGBGDROP_logs_v9_patch

files:
  alignment_pattern: "*.fasta"
  alignment_list: filelist.txt

tree:
  suffix_remove: ".fasta"
  suffix_add: ".tre"

analysis:
  model: busted
  srv: Yes
  error_sink: Yes